# Generated by Django 3.0.5 on 2020-05-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tod',
            new_name='Todo',
        ),
    ]
